### ISSUE TITLE
Canonical von ValueSets

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#101]
Einige Canonicals von ValueSets haben Typos (groß- und kleinschreibung) und das führt zu Errors beim CI Ablauf. Z.B.:
`error: Code '5-470' from system 'http://fhir.de/CodeSystem/bfarm/ops' does not exist in valueset 'http://fhir.de/ValueSet/bfarm/ops' warning: Terminology service failed while validating code '80146002' (system 'http://snomed.info/sct'): Cannot retrieve valueset 'https://gematik.de/fhir/IsiK/ValueSet/ProzedurenCodes-SCT' warning: Cannot resolve reference Encounter/patient Result: INVALID`

Sollte ggf. mit nächster TC gefixed werden.
FYI @alexzautke , @simoneOnFhir , @patrickwladowska

**Comment by f-peverali** [comment]
hat nichts mit typos zu tun, sondern das referenzierte VS enthält keine COdes (keine Expansion)

**Comment by alexzautke** [comment]
Solange kein Terminologie-Server bereitsteht, der in die Pipeline integriert werden kann, wird dieser Fehler bleiben.

**Comment by f-peverali** [comment]
Alles klar, danke für das Feedback
