### ISSUE TITLE
CapabilityStatement -  IG URL's entversionieren

### ISSUE THREAD

**Issue by patrickwladowska** [gematik/spec-ISiK-Basismodul#109]
Für die ISiK/ISiP - Module müssen im CapabilityStatement die Versionen entversioniert werden und duch funktionierende URL's ersetzt werden.

**Comment by alexzautke** [comment]
Ich muss leider meine Meinung ändern zu dem Thema. Die url sollte versioniert sein, da ansonsten keine Chance für den Client besteht zu erkennen welche Version von ISiK durch den Server implementiert wird.

**Comment by f-peverali** [comment]
kann das Ticket damit geschlossen werden @patrickwladowska ?
