### ISSUE TITLE
Invariants: Descriptions und Expressions

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#110]
Bei folgenden Invariants erscheinen die Descriptions Redundant bzw. die Expression falsch spezifiziert:

Invariant: sct-ops-1
Description: "Falls die Prozedur kodiert vorliegt, SOLL mindestens ein OPS oder SNOMED-CT Code angegeben werden. Liegt die Prozedur nicht kodiert vor SOLL Freitext angegeben werden."
Severity: #error
Expression: "(coding.exists() implies coding.where(system = 'http://snomed.info/sct').exists() or coding.where(system = 'http://fhir.de/CodeSystem/bfarm/ops').exists()) or (text.exists() and coding.exists().not())"

Invariant: proc-ISiK-3
Description: "Entweder MUSS eine kodierte Prozedur vorliegen oder eine textuelle Beschreibung. Stattdessen nur Extensions hinzuzufügen (vgl. https://www.hl7.org/fhir/element.html - ele-1), ist explizit nicht erlaubt."
Severity: #error
Expression: "coding.exists().not() implies text.exists()"

(1) Eine Frage zur Prüf-Semantik

bei sct-ops-1 :
(text.exists() and coding.exists().not()) -> dieser ausdrcuk wird immer als falsch ausgewertet, sobald ein Coding existiert, daher kann hiermit kein Vorhandensein des textes geprüft werden.
Für mich sieht die gesamte sct-ops-1 expression (und Descritpzion) probleamtisch aus, bzw. schlimmstenfalls führt sie dazu, dass die expression immer zu True auswertet.

(2) Eine Frage zur syntax:
Ist es tatsächlich erlaubt das "code" (z.B. für code.coding.exists() zu vernachlässigen?

(3) Der folgende Satz (Anforderung) aus sct-ops1 wird durch Expression proc-ISIK-3 abgedeckt : "Liegt die Prozedur nicht kodiert vor SOLL Freitext angegeben werden." -> d.h. redundant. Meines Erachtens sollte der Satz raus, auch weil man hier eigentlich 2 Anforderungen über eine Expression abzudecken versucht. D.h. auch, dass die Expression für sct-ops-1 dann lauten kann: 
`coding.exists() implies coding.where(system = 'http://snomed.info/sct').exists() or coding.where(system = 'http://fhir.de/CodeSystem/bfarm/ops').exists())` [hier noch die syntax fraglich]

@alexzautke Könntest Du hierzu bitte ein Feedback geben?

FYI @patrickwladowska 

---
merker : (code.coding.exists() implies code.coding.where(system = '[http://snomed.info/sct').exists()](http://snomed.info/sct%27).exists()) or code.coding.where(system = '[http://fhir.de/CodeSystem/bfarm/ops').exists()](http://fhir.de/CodeSystem/bfarm/ops%27).exists()) or code.text.exists() and code.coding.exists().not())

**Comment by f-peverali** [comment]
Sollten wir eine weitere Anforderung hinzufügen (um auszuschließen, dass ungenau Codiert wird)?
"Falls die Prozedur kodiert vorliegt, darf kein Text vorkommen." (Dies entspräche auch der Umsetzung in FHIR v5 mit Element Code statt Coding)

**Comment by alexzautke** [comment]
Nein, das wäre zu restriktiv

**Comment by alexzautke** [comment]
Die Constraints sehen alle korrekt aus. Der zweite Constraint ist auf dem code Element selbst definiert, deshalb “fehlt” der Teil im Pfad.

**Comment by patrick-werner** [comment]
Invariant: sct-ops-1:
`(text.exists() and coding.exists().not()) ` ist korrekt. Der Teil vor dem `or` ist dafür zuständig wenn coding vorhanden ist, der Teil danach ist zuständig für den Fall falls coding nicht vorhanden ist.

**Comment by patrick-werner** [comment]
Frage 3:
Ja, sct-ops-1 und proc-ISIK-3 überschneiden sich. Man könnte also  sct-ops-1 auf `(coding.exists() implies coding.where(system = 'http://snomed.info/sct').exists() or coding.where(system = 'http://fhir.de/CodeSystem/bfarm/ops').exists()) `verkürzen.

**Comment by f-peverali** [comment]
> Invariant: sct-ops-1: `(text.exists() and coding.exists().not()) ` ist korrekt. Der Teil vor dem `or` ist dafür zuständig wenn coding vorhanden ist, der Teil danach ist zuständig für den Fall falls coding nicht vorhanden ist.

Falls coding nicht vorhanden ist , dann wertet der Gesamtausdruck aber immer als true aus... nach logischem Prinzip ex-falso quodlibet bzw. truth-table hier https://build.fhir.org/ig/HL7/FHIRPath/#implies ... d.h. die Bracket dient mMn nie der Prüfung

Ich wäre dafür es zu verkürzen, wie du oben schreibst.

**Comment by f-peverali** [comment]
> Nein, das wäre zu restriktiv

Hatte mich da verlesen und Code statt CodeableConcept als datatype angenommen. Die Debatte kam häufiger bei MIO-Kommentierung auf, aber die Spez ist da eindeutig. 

Danke für euer Feedback!

**Comment by f-peverali** [comment]
für 2 done
für 1 todo
