### ISSUE TITLE
invariante in Patient-Datei

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#113]
https://github.com/gematik/spec-ISiK-Basismodul/blob/d3ee83fec523dbaa5bc766227059cfdf3b919cfc/Resources/input/fsh/invariants.fsh#L1

Diese Invariante wird ausschließlich zur Constraint-Bildung beim Patienten verwendet. 

(1) Ich würde diese Invariante in der entsprechende Datei definieren und die DAtei "invariants.fsh" selbst entfernen.

(2) Ggf. macht die (Wieder)einführung einer Datei "Invariants.fsh" Sinn (wie in Stufe 1), sobald Constraints Profilübergreifend genutzt werden. Oder?

Was sagt ihr? @alexzautke @patrickwladowska

**Comment by alexzautke** [comment]
@ylboerner @patrick-werner

**Comment by f-peverali** [comment]
... oder sollten doch alle invarianten in einer zentralen invariants.fsh-Datei vorgehalten werden?

**Comment by patrick-werner** [comment]
Wenn die Invariant nur in einer Ressource/Datei genutzt wird stimme ich dem Vorschlag zu. Es ist sinnvoll die Invariants im selben File zu haben.

**Comment by f-peverali** [comment]
FYi @patrickwladowska

**Comment by ylboerner** [comment]
@f-peverali Korrekt. Wir können zwischen diesen beiden Fällen unterscheiden: 

- Invariante in einem Profil genutzt -> Selbe Datei 
- Invariante in n Profilen genutzt -> `Invariants.fsh`

**Comment by f-peverali** [comment]
Fallunterscheidung und Hinweis wird in invariants.fsh dokumentiert

`#Only global invariants are defined in the present invariants.fsh file`

Beschluss mit @patrickwladowska

**Comment by f-peverali** [comment]
ggf. in Zukunft  noch für Basisstufe 1 begradigen?

**Comment by f-peverali** [comment]
Frage beantwortet, Ticket daher obsolet
