### ISSUE TITLE
Kompatibilitätsbetrachtung für Patient sollte Inkompatibilität zwischen KBV / ISiK in Address.country hervorheben

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Basismodul#117]
In Address.country verwendet die KBV im KBV Basismodul ein "extensible"-Binding auf die DEÜV-Codes. In ISiK fordern wir durchgehend die Verwendung von ISO-Codes. Dies sollte in den IG mit aufgenommen werden.

**Comment by f-peverali** [comment]
hat im Prinzip auch zur Folge, dass diese Aussage auch nicht mehr so gelten kann : "Instanzen, die gegen ISiKPatient valide sind, sind auch valide gegen:
* [Profil KBV_PR_Base_Patient der KBV Basisprofile - v1.2.1](https://simplifier.net/base1x0/kbvprbasepatient)"

**Comment by f-peverali** [comment]
IG Änderung vorgenommen
