### ISSUE TITLE
Composite SearchParameter für Encounter (Stufe 3!)

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiK-Basismodul#129]
Derzeit existiert Unklarheit im Bezug auf _repeated search parameters_ in der Suche mittels `date`. Zum Beispiel wird ein `Encounter` mit Suchanfrage `Encounter?date=ge2021-02-12&date=le2021-02-14` von HAPI FHIR und Firely Server und folgender `Period` unterschiedlich aufgelöst: 

```
"period": {
    "start": "2021-02-12",
    "end": "2021-02-14"
}
```

Da die Spezifikation hier unklar ist, sollten wir einen Composite SearchParameter für date-Searches auf `Encounter` definieren. Dieser sollte verlangen, dass die oben genannte Suchanfrage als ein logisches UND verstanden wird und AUSCHLIEßLICH Suchergebnisse enthält, für die beide Parameter wahr sind.

**Comment by f-peverali** [comment]
@jcaumanns könntest Du dir das Thema ansehen, sodass wir gemeinsam ein Lösung erarbeiten können?

**Comment by jcaumann** [comment]
Am Ende gibt es sogar vier Semantiken für das Zusammenspiel des Datentyps "period" und einer Suche über einem Zeitraum:
- die Suche ist positiv, wenn die "period" komplett im Suchfenster liegt
- die Suche ist positiv, wenn das Suchfenster komplett in der "period" liegt
- die Suche ist positiv, wenn der Start der "period" im Suchfenster liegt
- die Suche ist positiv, wenn das Ende der "period" im Suchfenster liegt
Zumindest zu drei davon fallen mir spontan gute UseCases ein. Müssen wir uns da wirklich auf eine Semantik festlegen oder können wir uns vor der Entscheidung drücken, indem wir nur Transparenz fordern, d.h. das System muss dokumentieren, wie es mit so einer Anfrage umgeht (zB in einem der documentation-Attribute des CapabilityStatement?

**Comment by f-peverali** [comment]
TODO

Lösungsoption:

- [ ] höchsten Recall fordern -> Problem hierbei nicht HAPI kompatibel (hier müsste die eine zusätzliche Suchanfrage implementiert werden ; ggf. sugar Change bei HAPI anfragen?)

**Comment by f-peverali** [comment]
@jcaumann hierzu sollten wir nochmal reden. Die [Spec](https://build.fhir.org/search.html#combining) ist zu Suchanfragen wie der obigen m.M.n klar darin eine (logische) intersection (Schnittmenge) zu fordern, also Ausschließend (wie @ylboerner oben schrieb).

**Comment by f-peverali** [comment]
Meiner Meinung nach ist die oben angegebene Suchanfrage `Encounter?date=ge2021-02-12&date=le2021-02-12` nicht Spezifikationskonform, da sich ein Wert wiederholt: "The parameter cannot repeat or have multiple values" (siehe http://hl7.org/fhir/encounter-search.html#clinical-date) 
@ylboerner d.h. ich sehe hier auch keinen Handlungsbedarf unsererseits. Oder übersehe ich etwas?

**Comment by alexzautke** [comment]
date-start und end-date sind nur Suchparameter in R5 und müssten noch als Custom Suchparameter in ISiK hinzugefügt werden

**Comment by jcaumann** [comment]
> date-start und end-date sind nur Suchparameter in R5 und müssten noch als Custom Suchparameter in ISiK hinzugefügt werden

mal wieder den gelben Balken übersehen, dass wir jetzt Sommerzeit und R5 haben....

Dann bleibt es bei dem ersten Satz aus meinem Kommentar. Deswegen jetzt R5 zu fordern, erscheint doch übertrieben. 
Wir sollten dann aber das in R5 formulierte Contraint "The parameter cannot repeat or have multiple values" in den Leitfaden übernehmen. In R4 gibt es leider zu den Suchparametern keine solchen Hinweise (oder ich habe zumindest keine an der Stelle gefunden, wo sie jetzt bei R5 sind); bedeutet aber auch, dass es in R4 keine gegenteilige Aussage gibt...

**Comment by alexzautke** [comment]
Sorry, wir haben uns missverstanden. Ich würde vorschlagen die beiden Suchparameter eins zu eins als Custom Suchparmeter als eigene Suchparameter in ISiK zu kopieren.

**Comment by alexzautke** [comment]
+1 für den neuen Hinweis

**Comment by alexzautke** [comment]
Vielleicht sollte man auch noch einen expliziten Hinweis geben, dass unerwartete Ergebnisse herauskommen bzw. überhaupt keine, wenn man auf date sucht aber die Period noch offen ist. Mit ein wenig Zeit und Mühe könnte man sogar das Thema mit einem kleinen Zeitstrahl darstellen.

**Comment by jcaumann** [comment]
Ich bin mir nicht sicher, ob man nicht den überwiegenden Teil der sinnvollen Suchen mit Hilfe der Prefixe "gt", "lt", "sa" und "eb" (siehe http://hl7.org/fhir/R4/search.html#prefix) umgesetzt bekommt. 
Mein Bild von FHIR ist immer noch das Paretoprinzip und wenn man die wesentlichen, realitätsrelevanten Dinge mit Bordmitteln hinbekommt, dann würde ich das mit den Custom Suchparametern sein lassen. Am Ende muss das dann ja auch immer jemand implementieren ...

**Comment by patrick-werner** [comment]
SearchParameter wurden aus R5 auf R4 gebackportet. Da einfacher als zwei einzelner SearchParameter, dadurch auch R5 Kompatibilität gegeben.

Dieser Backport erlaubt es effektiv auf Encountern zu suchen, falls end nicht gesetzt war erstreckt sich die period bis ins unendliche. Dadurch matchen beim Suchen zu viele Ressourcen. Dies wurde in R5 bereits gefixt, hier jetzt ebenfalls. Zudem war keine gezielte Suche auf Start oder Ende möglich. 

Dies stellt für Implementer keinen Aufwand dar, gängige Server/Libraries interpretieren SearchParameter einfach zur Laufzeit.

**Comment by patrick-werner** [comment]
> Danke @patrick-werner, wir werden den PR in die Stufe 3 mergen zur Kommentierung. Allerdings sind wir bei den Annahmen und Use Cases noch unsicher.

Kann ich euch da noch unterstützen? Gerne auch per kurzem Meeting

**Comment by f-peverali** [comment]
merge ist durchgeführt

**Comment by alexzautke** [comment]
@f-peverali Wir sollten hier ein neues Ticket ableiten um die Suche genauer zu erklären, eventuell wie oben vorgeschlagen mit einem Zeitstreifen und einer Erläuterung welcher Bereich von welchen Präfixen abgedeckt wird.
