### ISSUE TITLE
Mangel in Regex-Anagbe

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#132]
https://github.com/gematik/spec-ISiK-Basismodul/blob/3a4a3caa05edb3636fb066b37d74afc7da951f0a/Resources/input/fsh/ISiKBerichtSubSysteme.fsh#L89

Das ist nur ein Beispiel
Die ISiK Profile sollten auf Vorhandensein von "matches" überprüft werden. Es sollte auf genaue Angabe der Full-Match geachtet werden - also nicht Substring.

TODO for:

- [x] https://github.com/gematik/spec-ISiK-Basismodul
- [x] Stufe 1 – https://github.com/gematik/spec-ISiK-Basismodul/tree/master-isik-stufe-1
- [x] Stufe 2 – https://github.com/gematik/spec-ISiK-Basismodul/tree/master-isik-stufe-2
- [x] https://github.com/gematik/spec-ISiK-Terminplanung
- [x] https://github.com/gematik/spec-ISiK-Dokumentenaustausch
- [x] https://github.com/gematik/spec-ISiK-Sicherheit
- [x] https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasse
- [x] https://github.com/gematik/spec-ISiK-Medikation
- [x] https://github.com/gematik/spec-ISiP

Hintergrund: Ohne "^[...]$" (Dollarzeichen werden regex als Substring-Suche ausgewertet.
Siehe auch für Beispiel :https://simplifier.net/basisprofil-de-r4/identifieriknr Beispiel .value : ik-1:Eine IK muss eine numerische 9-stellige Zeichenkette (mit Prüfziffer) sein matches('^[0-9]{9}$')

**Comment by f-peverali** [comment]
@alexzautke: ich würde aus gegebenem Anlass analog für alle Module die Regex fixen. richtig?
AM Beispiel: soll ausschließen, dass der Term als Substring ausgewertet wird und damit zB ein falscher (zu langer KDL code) nicht als solcher erkannt wird.

**Comment by alexzautke** [comment]
Korrekt

**Comment by f-peverali** [comment]
Überprüft und keine weiteren Mängel gefunden fyi @patrickwladowska
