### ISSUE TITLE
User Stories für Beispiel-Instanzen

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#141]
Zu diskutieren:
Die Beispiel-Instanzen sollten eine User Story  folgen (analog zu #57 ) - ggf. auch in IG die User Story hinterlgen.
Für TC ab Dezember
```[tasklist]
### Tasks
- [ ] PTDATA-626
```

**Comment by f-peverali** [comment]
@MaxMTheilig magst Du dir das Ticket nehmen. Wenn Du eine "Nacharbeit" in dieser Form für falsch hältst, sollten wir das Ticket schließen.

**Comment by MaxMTheilig** [comment]
Schaue mir nochmal an und setze setze um, wo möglich.
