### ISSUE TITLE
markdown anpassen: auf Teile der Spezifkation verweisen können

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#143]
siehe https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/Links.20auf.20Abschnitte.20in.20der.20Spezifikation :
Marco Wedekind[6:00 PM](https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/Links.20auf.20Abschnitte.20in.20der.20Spezifikation/near/312674216)
Hallo gematik, (@Ansgar Hoeper , @Patrick Wladowska ),
ich möchte gern auf Teile der Spezifkation verweisen können, bspw. darauf, dass im Rahmen der Terminvereinbarung ein KIS die Anlage einer Patientenressource unterstützen muss. Es wäre super, wenn ihr die Abschnitte in der Doku verlinkbar macht. firely meint dazu:

To add to this, you can use https://ecotrust-canada.github.io/markdown-toc/ to generated MD index tables. That will also provide you with the links to the different headers, please be aware that this does not always work when there are special characters in the title name.

In the future we would like to add a feature like {{index:md-page}} so this works out of the box, but there is no timeline for that yet.```
```[tasklist]
### Tasks
- [ ] PTDATA-693
```

**Comment by f-peverali** [comment]
@patrickwladowska würde ich auch als hotfix machen, d.h. parallel zu TC-Release-Vorbereitung

**Comment by f-peverali** [comment]
FYI @MaxMTheilig passt ggf. zu deinen Ideen zur Umgestaltung der IGs

**Comment by alexzautke** [comment]
Feature-Request für Firely wurde eingereicht.
