### ISSUE TITLE
Kardinalität für composition.section.code

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#144]
zu Prüfen: Kardinalität für composition.section.code überall auf 1..1 setzen, damit das empfangende System die Referenz einordnen kann.
Vergleiche dazu: die Composition der MIO42 zum DiGA-MI

**Comment by alexzautke** [comment]
Das Profil in Stufe 1 und Stufe 2 wurde explizit dafür designed, dass keine Referenz notwendigerweise mitgeliefert werden. Erstmal sollte nur Freitext in section.text ausgetauscht werden. Mit Hinblick auf die Minimierung von Breaking Changes wäre meine Empfehlung es höchstens auf 0..1 MS setzen.
