### ISSUE TITLE
LOINC pattern / fixed value mit Document Summary sinnvoll?

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#145]
https://github.com/gematik/spec-ISiK-Basismodul/blob/46bc8b32be8a8dbd9ac04ba802da15df4a83d36e/Resources/input/fsh/ISiKBerichtSubSysteme.fsh#L25

Welchen Hintergrund hat es, dass "Document Summary" (LOINC) hier fixed ist? Erscheint mir nicht sinnvoll. 
LOINC als System würde ich lassen, aber den Code entfernen.

**Comment by alexzautke** [comment]
Aus meiner Sicht passt der Code schon relativ gut, da ein Bericht aus einem Subsystem meistens eine Zusammenfassung repräsentiert. Nur das System anzugeben ohne Code würde zu viele Freiheiten lassen. Ansonsten müsste man hier ein ValueSet-Binding mit einer entsprechenden Auswahl von Codes definieren.

**Comment by f-peverali** [comment]
Danke für das Feedback, @alexzautke. Damit erledigt
