### ISSUE TITLE
Alte Beispiele XML

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#146]
Hier sind noch Beispiele in XML hinterlegt, die u.a. in der Validierung Fehler werfen.
Wirkt auf mich veraltet und obsolet. Kann das weg? Oder werden die noch in IG referenziert? Wenn ja, dann auch Überarbeitung notwendig m.E.

**Comment by f-peverali** [comment]
Bsiepiel: ImplementationGuide/Examples/ISiKProzedur.xml
Error: Instance failed constraint sct-ops-1 "Falls die Prozedur kodiert vorliegt, SOLL mindestens ein OPS oder SNOMED-CT Code angegeben werden. Liegt die Prozedur nicht kodiert vor SOLL Freitext angegeben werden."
At: Procedure.code[0]
https://gematik.de/fhir/ISiK/StructureDefinition/ISiKProzedur|sct-ops-1

https://github.com/gematik/spec-ISiK-Basismodul/actions/runs/3590840950/jobs/6044678763

**Comment by f-peverali** [comment]
@patrickwladowska  , @alexzautke wisst ihr was zu den alten XML Beispielen?

**Comment by alexzautke** [comment]
Einige Beispiele wurden in Simplifier unter dem Examples Tab aufgeführt sind jedoch nicht in Git als FSH enthalten. Diese sollten gelöscht werden (falls sie es noch nicht sind)
