### ISSUE TITLE
Encounter kann nicht gerendert werden

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Basismodul#154]
https://simplifier.net/isik/isikkontaktgesundheitseinrichtung
und
https://simplifier.net/guide/implementierungsleitfadenisik-basismodul/ImplementationGuide-markdown-Datenobjekte-Datenobjekte-Kontakt?version=current#ImplementationGuide-markdown-KontaktGesundheitseinrichtung-Kontakt-Profil

--> The resource cannot be rendered.

**Comment by f-peverali** [comment]
alle images und StructureViews werden korrekt gerendered
