### ISSUE TITLE
Reference Prüfen

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#177]
Reference(...) aus StructureDefinition SOLLEN alle nur Core-Profile nutzen und keine ISiK-Profile.
Global für alle Module zu Prüfen und umzusetzen

- [x] https://github.com/gematik/spec-ISiK-Basismodul
- [x] Stufe 1 – https://github.com/gematik/spec-ISiK-Basismodul/tree/master-isik-stufe-1
- [x] Stufe 2 – https://github.com/gematik/spec-ISiK-Basismodul/tree/master-isik-stufe-2
- [x] https://github.com/gematik/spec-ISiK-Terminplanung
- [x] https://github.com/gematik/spec-ISiK-Dokumentenaustausch
- [x] https://github.com/gematik/spec-ISiK-Sicherheit
- [x] https://github.com/gematik/spec-ISiK-Vitalparameter-und-Koerpermasse
- [x] https://github.com/gematik/spec-ISiK-Medikation
- [x] https://github.com/gematik/spec-ISiP

Check
Extensions ausgespart, da für die COnstraint sinnvoll erscheint

- [ ] Releasenote anpassen

**Comment by f-peverali** [comment]
siehe https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BBasis.5D.20Coverage/near/322044640

**Comment by f-peverali** [comment]
spezifischer Fall siehe hier https://github.com/gematik/spec-ISiK-Basismodul/pull/175#issuecomment-1387195480 
sobald geklärt, für alle module systematisch zu prüfen

**Comment by alexzautke** [comment]
+1 Für den Check aller Module

**Comment by f-peverali** [comment]
ggf. als Breaking Change in Stufe und nicht als TC...
