### ISSUE TITLE
Slicing redundant?

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#181]
https://github.com/gematik/spec-ISiK-Basismodul/blob/01438b3737e042ff8d832fe80ebac0e8d1285bd8/Resources/input/fsh/ISiKAbrechnungsfall.fsh#L27

Denke das Slicing und die gesamte übergeordnete Struktur zu Element .subject sollte hier weg und ersetzt werden mit :
`* subject 1..1 MS only Reference(Patient)`

@ylboerner meine Du hattest schon mal eine Korrektur in die Richtung vorgenommen, oder täusche ich mich?

Die Struktur erzeugt Validierungsfehler mit dem Referenzvalidator (bzw. HAPI)

**Comment by alexzautke** [comment]
@patrick-werner und ich wollten uns zusammensetzen und gucken ob dies ein Fehler in HAPI ist. Haben es jedoch noch nicht geschafft. Das Slicing ist hier bewusst gewählt an der der Stelle. Eine Einschränkung auf nur Patient war nicht gedacht.

**Comment by f-peverali** [comment]
fyi siehe antwort alexzautke, @f-busch
