### ISSUE TITLE
Token modifier

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#199]
Es dürfen die Tokenmodifier :text und :not nur für Terminologiekonzepte mit coding oder codableConcept gelten.

AC:

TC mit Schärfung der Spec für Stufe 1 und 2 veröffentlichen

**Comment by f-peverali** [comment]
https://service.gematik.de/browse/PTDATA-122

**Comment by f-peverali** [comment]
@patrickwladowska könntest Du mir hierfür noch einen Hint geben, was genau anzupassen ist? Ggf. ein Positiv- oder Negativbeispiel?

**Comment by f-peverali** [comment]
Siehe z.B. IG 
"### Token

Die Modifier `:text` und `:not` MUSS für alle spezifizierten Suchparameter vom Typ 'Token' unterstützt werden."

**Comment by f-peverali** [comment]
Ändern nach 

"### Token

Die Modifier :text und :not MUSS für alle spezifizierten Suchparameter vom Typ 'code' und 'codeableConcept' unterstützt werden."

**Comment by alexzautke** [comment]
Die Änderung wäre fachlich nicht korrekt. Der Suchparameter ist vom Typ "Token" der auf ein Element vom Typ "code", "Coding" oder "CodeableConcept" zeigen kann. Der Typ des Elements ändert jedoch nicht den Typ vom Suchparameter.

**Comment by alexzautke** [comment]
Man könnten den Hinweis geben, dass ``:text`` auf Elementen vom Typ "code" wenig Sinn ergeben. Ich weiß aber nicht, ob dies nicht selbsterklärend ist, da kein Display-Wert existiert.

**Comment by f-peverali** [comment]
ggf. Ändern nach 

"### Token

Der Modifier :not MUSS für alle spezifizierten Suchparameter vom Typ 'Token' unterstützt werden, die auf ein Element vom Typ "Code", "Coding" oder "CodeableConcept" zeigen.

Die Modifier :text für alle spezifizierten Suchparameter vom Typ 'Token' unterstützt werden, die auf ein Element vom Typ "Coding" oder "CodeableConcept" zeigen."

**Comment by jcaumann** [comment]
@f-peverali : Gibt es einen Grund, warum das auf die Terminologie-Attribute eingeschränkt wird? Gemäß FHIR-Spec (https://www.hl7.org/fhir/search.html#token) sind auch Identifier Token und auch einige Basis-Typen können in der Suche wie Token behandelt werden. Wenn man das jetzt auf die kodierten Werte einschränkt - was ich durchaus für sinnvoll halte - dann sollte man das auch begründen. Auch sollte man sich überlegen, welches Verhalten man in Bezug auf Groß-Klein-Schreibung man erwartet bzw. bei den Tests als valide akzeptiert.

**Comment by f-peverali** [comment]
Das Argument war wohl der Implementierungsaufwand. Das ursprüngliche Ticket (und die Anforderung) kam von Dir @patrickwladowska . Könntest Du zu den Fragen von Jörg nochmal antworten?

**Comment by f-peverali** [comment]
HIntergrund für Einschränkung auf codeabConcept und Coding - besonders wichtig bei nicht festen (required) VAlueSet Bindings

**Comment by f-peverali** [comment]
Gibt es Use Cases, die durch die Einschränkung auf die o.g. Elemente ausgeschlossen werden?
-> nein , da keine Suchabfragen augeschlossen werden, sondern nur kein Bestandtiel des TEstverfahrens.

**Comment by f-peverali** [comment]
> Man könnten den Hinweis geben, dass `:text` auf Elementen vom Typ "code" wenig Sinn ergeben. Ich weiß aber nicht, ob dies nicht selbsterklärend ist, da kein Display-Wert existiert.

mit :text modifier kann auch display gematched werden, daher auch für code relevant, denke ich

**Comment by jcaumann** [comment]
@f-peverali : Mit "code" ist der Basistyp gemeint (http://hl7.org/fhir/datatypes.html#code), nicht das Attribut "code" eines kodierten Werts. Der Basistyp hat keinen "display".

**Comment by f-peverali** [comment]
@jcaumann es ging mir darum, dass es mit der o.g. Beispiel-Suchanfrage aus der Spec einen Case für den modifier :text auf code zu geben scheint. Möchte aber nicht darauf beharren. Mit ist ist es recht,  dies nicht explizit als Anforderung zu stellen - im Sinne der 2-Satz-Lösung oben (https://github.com/gematik/spec-ISiK-Basismodul/issues/199#issuecomment-1437155606) .
