### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#209]
https://github.com/gematik/spec-ISiK-Basismodul/blob/3949d483ae71f809a06aa2cf460a6b9835c6e573/ImplementationGuide/markdown/Patient/Patient_Kompatibilitaet.md?plain=1#L8

Hier unklar welches Profil gemeint
bei der MII finde ich im Personen-Modul https://simplifier.net/medizininformatikinitiative-modulperson/sdmiipersonpatient
mit version 2.0.0-ballot2
entspricht das der Version?
```[tasklist]
### Tasks
- [x] PTDATA-666
```

**Comment by f-peverali** [comment]
@patrickwladowska kannst Du mir hier weiterhelfen?

**Comment by patrickwladowska** [comment]
@f-peverali, genau das ist gemeint.

**Comment by f-peverali** [comment]
Das ehemals Verlinkte Package existiert so nicht mehr auf Simplifier.
Vor der Anpassung des Links ist ggf. Kompatibiltät zu prüfen

**Comment by f-peverali** [comment]
@MaxMTheilig hier sollten wir drüber reden, das ursprünglich harmonisierte Profil ist nicht mehr abrufbar. Hier der Link zur neuen Ballot version: https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.person/2.0.0-ballot3/files/2084783

**Comment by alexzautke** [comment]
@f-peverali Verlinke einfach auf die Canonical mit einem Resolve auf Simplifier. Dann kommt man auf der richtigen Seite raus.

**Comment by f-peverali** [comment]
@alexzautke Aber das ursprüngliche Profil kann ich dort nicht mehr finden. Der jetzige Arbeitsstand ist offensichtlich nicht kompatibel (siehe MS etc.)

**Comment by f-peverali** [comment]
Hier stellt sich die Frage nach der Kompatibilität mit MII konkret. Das sollten wir im Besonderen und allgemein angehen.

**Comment by ylboerner** [comment]
> Hier stellt sich die Frage nach der Kompatibilität mit MII konkret. Das sollten wir im Besonderen und allgemein angehen.

@f-peverali Der Scope dieses Issues wäre dadurch leider etwas zu groß. Ich kann den Link zum korrekten MII Profil derzeit nicht finden, auch das Package scheint verschwunden zu sein. Von daher entferne ich die Kompatibilitätsanmerkung erst einmal aus Stufe 2 und 3.

**Comment by ylboerner** [comment]
Stufe 3: https://github.com/gematik/spec-ISiK-Basismodul/pull/335

**Comment by ylboerner** [comment]
Stufe 2: https://github.com/gematik/spec-ISiK-Basismodul/pull/337

**Comment by f-peverali** [comment]
nicht nachzuziehen für Stufe 2
