### ISSUE TITLE
Prüfen ob Procedure.code.SNOMED MS -> AG Stufe 4

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#213]
https://github.com/gematik/spec-ISiK-Basismodul/blob/2b3cd3b0c533ded14157cb0b7834f3d6f81fa60f/Resources/input/fsh/ISiKProzedur.fsh#L33

Prüfen ob Poedcedure.code.SNOMED MS sein sollte.
@patrickwladowska - das meintest Du, richtig?

```[tasklist]
### Tasks
- [ ] PTDATA-677
```

**Comment by f-peverali** [comment]
@alexzautke Dn Hinweis hattest DU gegebn, richtig?

FYI @jcaumann

1. Welche Implikationen wären zu beachten, wenn SNOMED auch für den code der Prozedur MS würde? 
2. Was ist z.B. mit Systemen die derzeit SNOMED nicht verarbiten können? 
3. Ggf. nicht als TC möglich?

**Comment by alexzautke** [comment]
Genau. Zu beachten ist, dass es auf Condition.code bereits der Fall ist.
 1. Wir bräuchten einen Testfall
 2. Wie für die Condition müsste die Kodierung auch für Procedure im System eingeführt werden.
 3. Nein, da neuer Inhalt.

**Comment by f-peverali** [comment]
ok. Dann ggf. in Hotfix oder Stufe 3.
PR, der Testfall ausschließt ggf. obsolet: Wie für die Condition müsste die Kodierung auch für Procedure im System eingeführt werde

ggf. Testfall momentan als warning only ausgeben? FYi @patrickwladowska

**Comment by jcaumann** [comment]
Ich wäre grundsätzlich etwas vorsichtig, die Nutzung von SNOMED für procedure durch die MS-Einsortierung weiter aufzuwerten. Die procedure-Angaben fließen am Ende des Lebenszyklus des Falls in die DRGs ein und da wird OPS benötigt. SNOMED kann damit nur eine redundante Kodierung für eine Zweitnutzung dieser Information - z. B. für die Forschung - sein. Das rechtfertigt aber aus meiner Sicht kein MS (es sei denn es gibt auch einen starken Use Case aus der Versorgung, wo eine SNOMED-kodierte Prozedur erforderlich ist).

**Comment by alexzautke** [comment]
Für mich wäre eine Harmonisierung mit der KBV, hier den KBV Basisprofilen, ausschlaggebend.

**Comment by jcaumann** [comment]
Ein gutes Argument. Ich habe gerade mal in das neue MIO der KBV zum Krankenhausentlassbrief geschaut. Da sind auch beide auf MUST SUPPORT gesetzt, wobei in dem "Real World Beispiel" jedoch nur OPS ausgefüllt ist. 
Faktisch relevant ist das aber aktuell eh nur für Clientsysteme und da für Basis-2 nur KIS - und damit Serversysteme - bestätigungsrelevamt sind, sehe ich keine Eile, da jetzt akut etwas ändern zu müssen. Vielleicht sollte man erst noch mal eine Runde mit der KBV/MIO42 drehen und überlegen, wie man das am besten vereinheitlicht. Es gibt sicher noch andere Profile, wo ISIK und der KH Entlassbrief nicht ganz übereinstimmen.

**Comment by f-peverali** [comment]
> Ein gutes Argument. Ich habe gerade mal in das neue MIO der KBV zum Krankenhausentlassbrief geschaut. Da sind auch beide auf MUST SUPPORT gesetzt, wobei in dem "Real World Beispiel" jedoch nur OPS ausgefüllt ist. Faktisch relevant ist das aber aktuell eh nur für Clientsysteme und da für Basis-2 nur KIS - und damit Serversysteme - bestätigungsrelevamt sind, sehe ich keine Eile, da jetzt akut etwas ändern zu müssen. Vielleicht sollte man erst noch mal eine Runde mit der KBV/MIO42 drehen und überlegen, wie man das am besten vereinheitlicht. Es gibt sicher noch andere Profile, wo ISIK und der KH Entlassbrief nicht ganz übereinstimmen.

**Comment by f-peverali** [comment]
> Für mich wäre eine Harmonisierung mit der KBV, hier den KBV Basisprofilen, ausschlaggebend.

Momentan hat KBV Basis hier kein MS gesetzt : https://simplifier.net/packages/kbv.basis/1.4.0/files/1951744

**Comment by f-peverali** [comment]
Für Stufe 2 im Test warningOnly umgesetzt hier: https://github.com/gematik/ISiK-Testing/pull/207/files
... Grundsatzentscheidung steht aus (für Stufe 3)

**Comment by jcaumann** [comment]
> > Für mich wäre eine Harmonisierung mit der KBV, hier den KBV Basisprofilen, ausschlaggebend.
> 
> Momentan hat KBV Basis hier kein MS gesetzt : https://simplifier.net/packages/kbv.basis/1.4.0/files/1951744

Nach einer kurzen Stichprobe sieht es so aus, als ob bei den Basisprofilen nirgends ein MS gesetzt ist. Damit wären für uns alle Optionen offen....

**Comment by alexzautke** [comment]
In den meisten UseCase-spezifischen Projekten (in denen dann die MS-Flags gesetzt sind), ist der SNOMED-Slice MS. Zum Beispiel: https://simplifier.net/pka/kbv_pr_mio_nfd_condition
