### ISSUE TITLE
discriminator nicht erkannt (Stufe 2 und 1)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#222]
Im Bundle Profil taucht ein Fehler im Zusammenhang mit dem Slicing auf.

Discriminator in der Beispieldatei wird nicht gematched - siehe Error-Message:

21.03.23-11:25:54.137 [main] INFO  de.gematik.refv.cli.ReferenceValidator  - Validation result: Valid: false. Messages: 
SingleValidationMessage[col=6,row=24,locationString=Bundle.entry[0],message=Slicing cannot be evaluated: Could not match discriminator ([resource.type.coding.code]) for slice Bundle.entry:Composition in profile https://gematik.de/fhir/isik/v2/Basismodul/StructureDefinition/ISiKBerichtBundle - the discriminator [resource.type.coding.code] does not have fixed value, binding or existence assertions,SLICING_CANNOT_BE_EVALUATED,severity=error]
SingleValidationMessage[col=6,row=84,locationString=Bundle.entry[1],message=Slicing cannot be evaluated: Could not match discriminator ([resource.type.coding.code]) for slice Bundle.entry:Composition in profile https://gematik.de/fhir/isik/v2/Basismodul/StructureDefinition/ISiKBerichtBundle - the discriminator [resource.type.coding.code] does not have fixed value, binding or existence assertions,SLICING_CANNOT_BE_EVALUATED,severity=error]
SingleValidationMessage[col=6,row=119,locationString=Bundle.entry[2],message=Slicing cannot be evaluated: Could not match discriminator ([resource.type.coding.code]) for slice Bundle.entry:Composition in profile https://gematik.de/fhir/isik/v2/Basismodul/StructureDefinition/ISiKBerichtBundle - the discriminator [resource.type.coding.code] does not have fixed value, binding or existence assertions,SLICING_CANNOT_BE_EVALUATED,severity=error]
SingleValidationMessage[col=2,row=1,locationString=Bundle,message=Bundle.entry:Composition: Unable to check minimum required (Bundle.entry) due to lack of slicing validation (from https://gematik.de/fhir/isik/v2/Basismodul/StructureDefinition/ISiKBerichtBundle),Validation_VAL_Profile_NoCheckMin,severity=information]

**Comment by f-peverali** [comment]
Debug-Ansatz:

- Reihenfolge der System und Coding Angabe matched nicht zwischen Profil und Beispielinstanz; Ordnung wurde gematched, ist aber irrlevant, da Error fortbesteht
-

**Comment by f-peverali** [comment]
@f-busch : könntest Du den Punkt 4.1 testen, indem du den Discriminator aus der Composition für das Bundle-Profil einsetzt?

**Comment by f-peverali** [comment]
Das Slicing mit value im Bundle-Profil erfordert ein fixed value in den slicing (daher der fehler)
Da für das Composition-Slice ein [ISiKBerichtSubSysteme](https://simplifier.net/isik/files/resources/fsh-generated/resources/structuredefinition-isikberichtsubsysteme.json) gefordert wird, in dem Coding-Slicing mit pattern definiert, unklar, ob hier value-Discirminator auf Bundle-Ebene sinnvoll.

**Comment by f-peverali** [comment]
@jcaumann könntest Du hier einen Input geben?

**Comment by f-peverali** [comment]
TODO
- [ ] Slicing all slices macht vorgaben, beißt sich aber mit "open" Slicing.
- [ ] ggf. Forderung nach Composition und type.coding.code als CONSTRAINT

**Comment by f-peverali** [comment]
Der oben besprochene Lösungsansatz scheint nicht zu funktionieren. Denke Slicing mit discriminator.type = "profile" oder "exists" wäre  möglich. FYI @jcaumann

**Comment by alexzautke** [comment]
Ohne genau das Issue verstanden zu haben... "exist" möchte man in so gut wie keinen Fällen verwenden.

**Comment by f-peverali** [comment]
@alexzautke profile aber auch nicht (aus performance-gründen), oder?

**Comment by jcaumann** [comment]
@f-peverali : Was hat denn mit den Constraints nicht funktioniert? Eigentlich sollte sich das alles über FHIRPath ausdrücken lassen.

**Comment by f-peverali** [comment]
@jcaumann die Beispielinstanz validiert nicht gegen das Bundle-Profil. Mit folgendem Fehler: https://github.com/gematik/spec-ISiK-Basismodul/commit/80ae41c6c096202700fc03a28d1978bd2db2573d

**Comment by jcaumann** [comment]
> 
dann prüfe doch einfach auf Composition und dann in der Composition auf meta.profile. Das ist ja ein Pflichtfeld...

**Comment by jcaumann** [comment]
ich glaube ich habe den Fehler: "resource.is" geht nur auf den Ressourcetyp, während "ofType" wohl auch abgeleitete Typen erfasst. Versuch doch bitte mal "Bundle.entry.resource.ofType(ISiKBerichtSubsystem).count = 1"

**Comment by f-peverali** [comment]
> ich glaube ich habe den Fehler: "resource.is" geht nur auf den Ressourcetyp, während "ofType" wohl auch abgeleitete Typen erfasst. Versuch doch bitte mal "Bundle.entry.resource.ofType(ISiKBerichtSubsystem).count = 1"

ich teste es ....

**Comment by alexzautke** [comment]
Die korrekte Methode wäre "conformsTo", ich bin mir jedoch nicht sicher, ob der Java Validator diese implementiert...

**Comment by alexzautke** [comment]
Siehe https://www.hl7.org/fhir/r4/fhirpath.html

**Comment by f-peverali** [comment]
> Die korrekte Methode wäre "conformsTo", ich bin mir jedoch nicht sicher, ob der Java Validator diese implementiert...

wird scheinbar nicht implementiert: "warning: Compilation of FhirPath for constraint 'ISiK-docBundle-2' failed: Unknown symbol 'conformsTo' "

**Comment by f-peverali** [comment]
Gelöst mit Slicing tytpe "type" , hier :https://github.com/gematik/spec-ISiK-Basismodul/pull/202
TODO analog für Stufe 1

**Comment by f-peverali** [comment]
für Stufe 1 gilt vereinfachtes Beispiel ohne slicing. Daher keine analoge Änderung notwendig
