### ISSUE TITLE
fix canonicals 

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#241]
einige Elemente, die aus den Basisprofilen DE stammen werden in simplifier nicht mehr gerendert, obwohl die dependencies unverändert sind (auch in simplifier wird Basisprofil DE 1.4.0 angezeigt). Beispiel Error-Message:

`Some canonical urls could not be resolved.
You're probably missing a package or made a typo in your canonical.
Could not resolve: http://fhir.de/StructureDefinition/ProzedurDokumentationsdatum
Could not resolve: http://fhir.de/StructureDefinition/CodingOPS`

siehe in simplifier https://simplifier.net/isik-v3/isikdiagnose
oder https://simplifier.net/isik-v3/isikprozedur

---
off topic:
canonical claim auf "v3" und alle canonicals angepasst

- [x] beachte sourcecode 
  - [x] alias
  - [x] sushi-config
  - [x] canonical-claim
- [x] und insbesondere capability statement

**Comment by f-peverali** [comment]
@patrickwladowska , @alexzautke , @patrick-werner , wisst ihr woran das liegen könnte?

**Comment by alexzautke** [comment]
Wahrscheinlich musst du im Dependency-Tab einmal manuell auf Restore klicken

**Comment by f-peverali** [comment]
Top; DANKE @alexzautke, das war es
