### ISSUE TITLE
Satz entfernen (Kommentierung Stufe 3?)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#245]
Mit der Stufe 3 haben wir einen Abrechnungsspezifischen Account-identifier eingeführt, der im Encounter (als account.identifier) mitgeführt werden muss. Dieser Satz sollte aber nicht mehr gelten, richtig @jcaumann ?

https://github.com/gematik/spec-ISiK-Basismodul/blob/ba4912ddfa19af2aa98cf033f6af237a15f105ca/ImplementationGuide/markdown/Abrechnungsfall/Abrechnungsfall_AnmerkungenZuDenMustSupportFeldern.md?plain=1#L7
```[tasklist]
### Tasks
- [ ] PTDATA-685
```

**Comment by jcaumann** [comment]
> Mit der Stufe 3 haben wir einen Abrechnungsspezifischen Account-identifier eingeführt, der im Encounter (als account.identifier) mitgeführt werden muss. Dieser Satz sollte aber nicht mehr gelten, richtig @jcaumann ?
> 
> https://github.com/gematik/spec-ISiK-Basismodul/blob/ba4912ddfa19af2aa98cf033f6af237a15f105ca/ImplementationGuide/markdown/Abrechnungsfall/Abrechnungsfall_AnmerkungenZuDenMustSupportFeldern.md?plain=1#L7

Wenn ich mich recht entsinne, war die Motivation für den neuen Identifier, dass der "Krankenhausabrechnungsfall" im KIS aus mehreren Aufenthalten bestehen kann, die jeweils ein Encounter sind. Um die Bindung an den Abrechnungsfall im KIS herzustellen, wird dann der neue Account Identifier verwendet. So zumindest meine Erinnerung an die Diskussion. 
@alexzautke : ich glaube, du warst in der Diskussion mit dabei. Stimmt da meine Zusammenfassung?

**Comment by alexzautke** [comment]
Korrekt. Die Frage ist ob man den Hinweis gibt, dass es ein dieser Identifier entweder ein komplett eigenständiger Identifier ist, der mehrere Encounter zusammenhält wie oben beschrieben ODER ein neuer Identifier mit dem Identifier **Value** aus dem (einzigen) dazugehörigen Encounter (mit einem neuen Identifier type).

**Comment by f-peverali** [comment]
Satz muss erweitert werden
