### ISSUE TITLE
Coverage identifier inkonsistent 

### ISSUE THREAD

**Issue by markus020** [gematik/spec-ISiK-Basismodul#250]
Im Profil ISiKVersicherungsverhaeltnisGesetzlich sind die identifier inkonsistent:
1) die Definition des identifier sagt, dass primär die 30-stellige Krankenversicherungsnummer verwendet werden soll und die 10-stellige KVNR nur, wenn diese unbekannt ist. Das beißt sich aber mit den Kardinalitäten -> fehlt hier ein Slice für die 30-stellige? 
2) bei beneficiary sagt der Kommentar, dass die Angabe der 10-stelligen KVNR verpflichtend ist, aber das spiegelt sich nicht in der Kard. wieder (hier wäre tatsächlich dann die 10-stellige KVNR 2x aufgeführt) -> Auflösung mittels Constraint? 

Zusätzlich ist der zugehörige Testfall ebenfalls inkonsistent (der Patient hat in der Patientenressource eine andere 10-stellige KVNR als in der Coverage) 

Siehe weitere Informationen in der Zulip-Diskussion: https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BBasis.5D.20Coverage/near/349073762
```[tasklist]
### Tasks
- [ ] PTDATA-664
```

**Comment by f-peverali** [comment]
FYI @jcaumann

**Comment by f-peverali** [comment]
@patrick-werner, @alexzautke 
zu Punkt 1. würde ich diesem ticket (https://hl7germany.atlassian.net/browse/HFB-57) folgen und den entsprechenden Text auch in unserem Profil/IG entfernen ? Also "Ein gesetzliches Versicherungsverhältnis sollte stets durch die eindeutige 30-stellige Versichertennummer identifiziert werden... "etc 

Zu 2.: Verstehe ich es richtig, dass hier eine eine Informative Änderunge hinzu sollte im Sinne dieses Tickets? https://hl7germany.atlassian.net/browse/HFB-58

Grundsätzlich scheint der Bedarf nach einer robusteren ID gegenüber der 10-Stelligen noch nicht aufgelöst, wenn ich mir das hier ansehe: https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BBasis.5D.20Coverage/near/349073762
Sollten wir das nochmal Aufgreifen in der Bearbeitung?

**Comment by patrick-werner** [comment]
Nach heutiger Diskussion wurden folgende Todos beschlossen:
- subscriber & subscriber.identifier werden MS
- beneficiary ^comment ist falsch: die Angabe der reference sollte verpflichtend sein, der Identifier ist optional (auch kein MS)
