### ISSUE TITLE
Account.subject - unnötiger/missverständlicher Slice (Kommentierung Stufe 3)

### ISSUE THREAD

**Issue by markus020** [gematik/spec-ISiK-Basismodul#251]
das Element Account.indentifier ist gesliced und hat einen Slice mit Name "PatientISiK", referenziert jedoch gemäß der Design-Entscheidung (https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BBasis.5D.20Coverage/near/322044640) nur auf die Core-Ressource. Hier wäre eine Einschränkung auf Patient als targetProfile ausreichend.

**Comment by alexzautke** [comment]
Das Problem ist hier, dass subject ausnahmsweise eine Kardinalität von 1..* hat und zusätzlich auf weitere Ressourcen außer Patient verweisen kann. Die Idee dahinter war, dass die Referenz auf Patient verpflichtend ist. Man könnte überlegen, ob ein FHIRPath Constraint hier schöner ist als der Slice.

**Comment by markus020** [comment]
ja das hab ich auch gerade gesehen. Ist mir jetzt erst beim 3. mal drüber schauen aufgefallen, weil versucht habe herauszufinden, was der PatientISiK-Slice macht. Ich habe ihn tatsächlich als Überbleibsel gesehen, als die Referenzen noch auf die Profile angedacht waren. 

Ich fände hier einen Constraint "schöner" bzw.  zumindest eine Umbenennung, damit man nicht etwas ISiK-spezifisches erwartet (fände Constraint trotzdem besser).

**Comment by patrick-werner** [comment]
Ein constraint ist aber leider weniger sichtbar als ein Slice und wird evtl. eher übersehen.

**Comment by simoneOnFhir** [comment]
Brauchen wir in DIESEM Account-Profil (das ein Fall-Abrechnungsklammer darstellen soll) die Möglichkeit auf irgendetwas anderes als einen Patienten zu referenzieren? Ich versuche gerade, mir einen UseCase auszudenken und schaff's nicht.

**Comment by alexzautke** [comment]
Was wäre mit einem Tracking der Fachabteilungen über den Einrichtungskontakt hinweg (aka Tracking der HealthcareServices)?

**Comment by f-peverali** [comment]
> Was wäre mit einem Tracking der Fachabteilungen über den Einrichtungskontakt hinweg (aka Tracking der HealthcareServices)?

Wofür wäre das zum Beispiel nützlich?

**Comment by f-peverali** [comment]
Gibt es Gegenstimmen zur Umbenennung des Slices von "PatientISiK" zu "Patient"? 
FYI @jcaumann

**Comment by jcaumann** [comment]
> Was wäre mit einem Tracking der Fachabteilungen über den Einrichtungskontakt hinweg (aka Tracking der HealthcareServices)?

das würde man dann aber wahrscheinlich nicht in dieses Profil packen, sondern dazu ein separates Profil bauen. Das ist ja doch sehr speziell und betrifft dann sicher auch noch andere Elemente.

**Comment by jcaumann** [comment]
> Gibt es Gegenstimmen zur Umbenennung des Slices von "PatientISiK" zu "Patient"? FYI @jcaumann

Das ist natürlich Geschmacksache, aber ich bin eher ein Freund davon, auf Slices zu verzichten, wenn man das auch gut als Constraint ausdrücken kann. Da in diesem Fall der UseCase aber sehr eng und klar definiert ist, finde ich Simones Vorschlag (Patient 1..1 ohne Slice und Constraint) am klarsten und besten.

**Comment by f-peverali** [comment]
Sollten wir das auch noch für Stufe 2 in einer Technical Correction nachziehen, @patrick-werner, @ylboerner , @simoneOnFhir , @MaxMTheilig ?  (FYI @alexzautke )

**Comment by ylboerner** [comment]
@f-peverali Wenn sich die letzte Frage auf [diesen Commit](https://github.com/gematik/spec-ISiK-Basismodul/commit/57b38931232a45ffb3f61f42b3dc6dfd7fd1fdfe) bezieht, ist die Änderung meiner Meinung nach nicht ausreichend für eine Technical Correction. Hier wird nur der Slice entfernt, um die Usability zu verbessern. Für mich würde es reichen, dies in Stufe 4 umzusetzen. Ich lasse mich aber gerne überstimmen 👍

**Comment by f-peverali** [comment]
@ylboerner Die Änderung ist bereits in Stufe 3 eingegangen. Die Frage lautet: sollten wir die Änderung nachträglich auch noch für Stufe 2 als TC übernehmen, oder belassen wir es beim Status quo? Aber mit der Antwort bin ich dahingehend einverstanden, dass der Status quo  in Stufe 2 bleiben soll und wir keine Änderung vornehmen... und ich kann das Ticket schließen.
