### ISSUE TITLE
Sollten externe Patient-Ressourcen als Extern nach Übernahme gekennzeichnet bleiben? (Kommentierung Stufe 3)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#254]
“Sollte die erzeugte Ressource dauerhaft in das bestätigungsrelevante System übernommen werden, MUSS der entsprechende Tag in Patient.meta.tag entfernt werden. In diesem Falle MUSS die id der Ressource stabil bleiben und darf nicht verändert werden.“

Siehe https://simplifier.net/guide/implementierungsleitfadenisik-basismodul/I-markdown-UebergreifendeFestlegungen-UebergreifendeFestlegungen-Rest?version=current

Es sollte besprochen werden, ob es nicht besser im Sinner der Provenance ist, dass der meta.tag bestehen bleibt um anzugeben, dass es sich ursprünglich um eine extern angelegte Ressource handelt und die Informationen nicht im KIS erhoben wurden.

---
Anfrage von @alexzautke

**Comment by markus020** [comment]
Ich denke, dass man das pauschal nicht sagen kann. Ein Beispiel, bei welchem das aus meiner Sicht nicht funktionieren würde sind Patienten: diese könnten "extern" z.B. aus einem Patientenportal kommen; sollen diese fest in das Primärsystem übernommen werden, ist das i.d.R. mit einer Validierung der Angaben (Einlesen einer eGK oder anderweitiger Identitäts-/Versichertennachweis) verbunden. Da eine "externe" Ressource bzw. deren Informationen ggfs. als nicht gesichert gelten und daher vermutlich mit Einschränkungen verbunden sind, kann dies hier zu Problemen führen -> z.B. die "externe"-Patientenressource wird nach Aufnahme mit eGK-Einlesen depricated und durch eine neue ersetzt (also wird nicht die externe Ressource aktualisiert bzw. dauerhaft persistiert, sondern faktisch neu erhoben). 

Ich denke, dass für die Provence andere Mechanismen geeigneter sind und würde hier sogar die verpflichtende Umsetzung dieses Tags insgesamt in Frage stellen und dies in die Verantwortung des Systems legen, wie es mit Ressourcen von Subsystemen umgehen möchte.

**Comment by alexzautke** [comment]
"[...] Patientenressource wird nach Aufnahme mit eGK-Einlesen depricated und durch eine neue ersetzt [...]". Die Intention der Spezifikation war eigentlich genau dies zu vermeiden. Aus meiner Sicht hat dies den Nachteil, dass viele Referenzen "ins leere Laufen", da es noch keine gute Lösung für das Merging von Patienten gibt. Es sollte dem System offen gelassen werden, ob es überhaupt Daten aus der externen Ressource übernimmt. Die Ressource kann auch mit der eigenen Interpretation überschrieben werden. Daher kam auch die Überlegung in diesem Fall den Tag zu löschen. Falls der Tag bestehen bleibt könnte man somit noch nachvollziehen, dass sich irgendwann man um eine externe Ressource gehandelt hat.

**Comment by markus020** [comment]
Ich sehe es auch so, dass ein "Ersetzen" wo immer möglich verhindert werden sollte, da es für Merges kaum "FHIR-taugliche" geschweige denn einheitliche Lösungen gibt. Das gilt ja auch nicht nur für Patient-Ressourcen. 

Ich würde die Vorgabe (MUSS) streichen und ggfs. als Best-Practice oder Möglichkeit zur Provenance einer extern erstellten Ressource drinnen lassen. Wichtig ist aus meiner Sicht, dass es a) einem System überlassen sein sollte, ob es eine bestimmte Ressource direkt rund b) sofern es eine Ressource übernimmt, selbst für die Provenance verantwortlich ist.

**Comment by alexzautke** [comment]
+1

**Comment by f-peverali** [comment]
Fazit wäre also den aus dem anfangs zitierten Satz das "MUSS" je zu Streichen und ggf. die Aussage als (informative) Best-Practice zu kennzeichnen. Wäre das eine Änderung, die auch für Stufe 1 und 2 relevant wäre (als TC)?
@jcaumann Was sagst Du dazu?
