### ISSUE TITLE
CapabilityStatement Composition (Kommentierung Stufe 3)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#259]
TODO : Composition Read SHALL entfernen

---
Anfrage:

Im CapabilityStatement wird die Ressource Composition als Read Shall angegeben → lt. Interaktion beim Datenelement ist für den BerichtSubSysstem jedoch nicht vorgesehen. UC für das Abrufen einer Composition ist fraglich

**Comment by f-peverali** [comment]
@jcaumann stimmst Du der Umsetzung zu?

**Comment by jcaumann** [comment]
> @jcaumann stimmst Du der Umsetzung zu?

Ja.
Ein Lesen macht in den im IG genannten Szenarien keinen Sinn, da die Zusammenstellung des Dokuments durch das Subsystem erfolgt, d.h. für die logische Identifizierung des Dokuments (einschießlich des Wissens zur Existenz des Dokuments) Subsystem-Wissen erforderlich ist, was das Primärsystem bei den im Fokus stehenden UseCases nicht hat. Im Kern sieht das so aus wir eine FHIR-Version der HL7v2 MDM T02 Nachricht, zu der es auch kein lesendes Pendant gibt. 

Prinzipiell sollten natürlich auch lesende Operationen auf ein Dokument möglich sein.
Beispiel: Ein Krankenhaus nutzt eine dedizierte Software für die Medikationsverwaltung. Das KIS will von dieser Software das Dokument "Medikationsplan" abrufen. Vergleichbares ist auch für andere MIOs denkbar. 
Dies würde dann aber ziemlich sicher nicht durch ein "read" auf die Composition-Ressource erfolgen. @f-peverali : Oder doch? Falls "ja" oder "vielleicht", sollten wir doch noch einmal nachdenken...

**Comment by f-peverali** [comment]
@jcaumann: Ich lesen die Spec als unidirektionalen Bericht. Richtig @alexzautke ? 
Weitere UC können wir für folgende Stufen erörtern.

`Dies würde dann aber ziemlich sicher nicht durch ein "read" auf die Composition-Ressource erfolgen`
Für den von Dir genannten Use Case würde ich auf die Suchabfragen im Medikationsmodul verweisen: https://simplifier.net/guide/isik-medikation/ImplementationGuide-markdown-CapabilityStatement?version=current bzw auf die Rollen hier: https://simplifier.net/guide/isik-medikation/ImplementationGuide-markdown-AkteureUndInteraktionen?version=current

**Comment by alexzautke** [comment]
Korrekt

**Comment by oliverhuda-dedalus** [comment]
@f-peverali Dise Änderung sollte zusätzlich auch in in Stufe 2 angewandt werden. Dort besteht er in der Spezifikation weiterhin und hat zumindest in userem Team Verwirrung gestiftet.

**Comment by f-peverali** [comment]
obsolet
