### ISSUE TITLE
Account identifier VS (Kommentierung Stufe 3)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#267]
Für das Profil IdentifierAbrechnungsnummer sollte  ein konsistentes VS formuliert werden.

---

Ursprüngliche Anfrage:

Das VS für den Account.identifier enthält den geforderten Code (noch) nicht. Zwar ist das VS extensible, aus Gründen der Stringenz sollte das VS jedoch vollständig sein und auch grundsätzlich keine Abhängigkeiten in die Zukunft (“hier wird eine Anpassung erfolgen”) geschaffen werden.

**Comment by f-peverali** [comment]
@jcaumann hier habe ich noch eine Änderung erzeugt, die wir noch nicht besprochen hatten. Ist im Wesentlichen eine Frage der Konsistenz (technisch) und ändert nichts an fachlichen Vorgaben.

**Comment by f-peverali** [comment]
FYI @markus020

**Comment by jcaumann** [comment]
> @jcaumann hier habe ich noch eine Änderung erzeugt, die wir noch nicht besprochen hatten. Ist im Wesentlichen eine Frage der Konsistenz (technisch) und ändert nichts an fachlichen Vorgaben.

siehe meine Kommentare im Markdown: Der Code AN ist meiner Meinung nach falsch, da sich der "Account" hier nicht auf einen "Patient Account", sondern einen "Bank Account" bezieht und somit AN eine Kontonummer auszeichnet.
