### ISSUE TITLE
TC 2?/3/4 - SNOMED Code Ändern Procedure

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#286]
Code ist zu ändern in ISiK Basismodul ( und ggf. in anderen)

---

Hier der Hinweis von KBV / Max Reith:

wir arbeiten gerade an einer neuen Version der KBV.Basis und aktualisieren auch immer die Snomed-Version. Dabei ist aufgefallen, dass ein Code, den wir Alle nutzen, obsolet ist und ersetzt werden muss:
procedure.category 

alter Code: 103693007 Diagnostic procedure (procedure)
neuer Code: 165197003 |Diagnostic assessment (procedure)|

```[tasklist]
### Tasks
- [ ] PTDATA-669
```

**Comment by f-peverali** [comment]
@MaxMTheilig auch das wäre ein Breaking Change und entsprechend zu kommunizieren.

**Comment by f-peverali** [comment]
zur info: Code ist inactive (kann daher z.B. von OntoServer nicht verarbeitet werden)

**Comment by MaxMTheilig** [comment]
Der neue Code sollte Stufe 4 und 3 umgesetzt werden.
Bei Stufe 2 könnte überlegt werden ihn zusätzlich aufzunehmen. Generell muss man sich überlegen wie eine Übergangsphase gestaltet werden kann.

**Comment by f-peverali** [comment]
Da Stufe 2 Bestätigung noch nicht weit fortgeschritten, lohnt sich hier ein Fix.

**Comment by f-peverali** [comment]
@MaxMTheilig du hast damit schon angefangen, beizehungsweise wolltest das heute noch tun, oder? Falls ja, könntest Du das Ticket übernehmen? Andernfalls weise es mir wieder zu, dann setze ich das zunächst für TC 3.0.1 um
