### ISSUE TITLE
Unconvential searchparameter naming for Encounter

### ISSUE THREAD

**Issue by MaxMTheilig** [gematik/spec-ISiK-Basismodul#289]
In "main-isik-stufe-3/Resources/input/fsh/ISiKKontaktGesundheitseinrichtung.fsh" searchparamaters are named contra intuitive: date-**start** and **end**-date.

should be **start-date** to match with the other variables in the project
```[tasklist]
### Tasks
- [ ] PTDATA-694
```

**Comment by alexzautke** [comment]
Das ist der Name der Suchparameter wie in FHIR R5. Siehe https://build.fhir.org/encounter.html#search
