### ISSUE TITLE
Anforderung eindeutiger Service-BaseURL

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Basismodul#312]
### Reference Issues

 see #308 

### Summary

Die Anfrage auf Datenhaltende-Systeme muss so gestaltet sein, dass es aus Perspektive des Clients nur eine Service-BaseUrl gibt.

die Klarstellung zur Client-Sicht in der Basis textuell (informativ) festgehalten werden. Ggf hier als erstes: https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Basismodul-Stufe-3/markdown-UebergreifendeFestlegungen-UebergreifendeFestlegungen-Rest?version=current

Siehe : https://github.com/gematik/spec-ISiK-Terminplanung/pull/133

### Common Examples

Anforderungs-Beispiel im Falle der Terminplanung: Das Termin-Repository muss so gestaltet sein, dass es aus Perspektive des Clients nur eine Service-BaseUrl gibt.

### Drawbacks

-

```[tasklist]
### Tasks
- [ ] PTDATA-705
```

**Comment by f-peverali** [comment]
am besten umsetzen mit [#312](https://github.com/gematik/spec-ISiK-Basismodul/issues/308)

**Comment by alexzautke** [comment]
Siehe https://service.gematik.de/browse/PTDATA-705
