### ISSUE TITLE
SCT bindings: version sollte überall mandatory gesetzt werden

### ISSUE THREAD

**Issue by patrick-werner** [gematik/spec-ISiK-Basismodul#314]
- [ ] überprüfe alle Stellen mit SCT bindings, version sollte überall mandatory gesetzt werden
- [ ] Feedback aus Community einholen: sollten wir auch die SCT Version vorgeben?

 
```[tasklist]
### Tasks
- [x] PTDATA-671
```

**Comment by abiernat-cerner** [comment]
Was ist der Rationale die Vesion mitzuführen? Die Konzept-Codes bleiben stabil. Natürlich sind diese auch einem Lebenszyklus unterworferen. In Konsequenz würde diese Idee dazu führen, das es monatlich neue Profil versionen geben muss, da SNOMED CT diese Taktung beim Release hat.

**Comment by alexzautke** [comment]
@julsas @patrick-werner Könntet ihr nochmal darstellen wo die Konzept-Codes nachweislich nicht stabil geblieben sind? Die mio42 hatte hier bereits auch angemerkt, dass praktische Probleme entstehen.

**Comment by f-peverali** [comment]
> @julsas @patrick-werner Könntet ihr nochmal darstellen wo die Konzept-Codes nachweislich nicht stabil 
Hilft das hier ? https://github.com/gematik/spec-ISiK-Basismodul/pull/322/commits/d72f3a08a41b999074b4f33db299d5d71cd04be9

**Comment by mmreith** [comment]
es gibt hier m.E. mehrere min. theoretische Probleme, die immer auch mit einem vorhandenen SCT-Terminologieserver stehen
1. implizite VS
Bei impliziten Codes können sich Codes die zum Zeitpunkt A gedacht waren im Zeitpunkt B plötzlich nicht mehr oder an ganz anderer Stelle (Hierarchie) wiederfinden, daher wäre eine Versionsangabe hier sehr sinnvoll.
2. bei dezidierten Codes
 - Es gibt öfter Codeänderungen bei denen Codes deprecated gesetzt werden. Mit einem Terminologieserver könnte man dann herausbekommen bis wann dieser akutell war und wie dieser ausgetauscht worden ist. In unserem ambulanten Umfeld ist sowas derzeit zumindest nicht vorauszusetzen. 

Wir haben uns daher vorgenommen explizite Versionen vorzugeben und dann auch in den Instanzen zu verlangen. Dann auch mit Display, damit man auch ohne TermServer alles beisammen hat.

**Comment by julsas** [comment]
Konkret betroffen war jetzt in dem Prozeduren Kategorien ValueSet der Code 103693007 |Diagnostic procedure (procedure)|, der ab der April 2023 Version von SNOMED inactive ist. Heißt, Terminologie Server mit einer aktuelleren SNOMED Version expanden das ValueSet nicht mehr korrekt. Daher kam von der KBV der Vorschlag, stattdessen 165197003 |Diagnostic assessment (procedure)| zu nehmen. 
Im Prinzip wissen wir nicht, welche Codes in Zukunft stabil/active bleiben. Wir könnten also `ValueSet.compose.include.version` vorgeben.
