### ISSUE TITLE
🐛 [BUG] - Account Beispiel AbrechnungsfallAmbulant zweifelhaft

### ISSUE THREAD

**Issue by abiernat-cerner** [gematik/spec-ISiK-Basismodul#348]
### Description

Das Example AbrechnungsfallAmbulant zum Account Profile hilft uns bei der Implementierung kaum weiter. 
Fachlich sehe ich einen Abrechnungsfall im Ambulanten Setting der mit DRGs(!) abgerechnet. 
Meines Wissens ist des nicht abbildbar im Versorgungsalltag.
Es fehlen auch diversen Extensions und Referenzen zu Diagnosen und Prozeduren.
Bitte um Überarbeitung

### Reproduction URL

https://simplifier.net/isik-basis-v3/resources-fsh-generated-resources-account-abrechnungsfallambulant

### Version or Branch

basis v2 und basis v3

### Reproduction Steps

```bash
N/A
```

**Comment by f-peverali** [comment]
Danke für den Hinweis, das schauen wir uns an (PTDATA-82).

**Comment by alexzautke** [comment]
In Stufe 5 ist geplant die ambulanten Fälle besser aufzubereiten. Im Zuge eines größeren Epics werden wir dieses Ticket erstmal schließen. Das Beispiel wird zu einem DRG-Fall angepasst.
