### ISSUE TITLE
ISiKBerichtSubsystem: Spec sollte Beispiel für Bundle enthalten

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Basismodul#57]
Momentan ist nur die Composition abgebildet. Das Beispiel sollte erweitert werden, sodass die Composition in das Bundle eingebunden ist. Optional sollten weitere Ressourcen als Entries vorhanden sein.

**Comment by f-peverali** [comment]
Frage an mich: welche Beispiel-Ressource hier am Besten geeignet zusätzlich?

**Comment by jcaumann** [comment]
Syntaktisch sieht das Bundle-Beispiel korrekt aus, aber ich habe damit drei inhaltliche/semantische Probleme:
1. Die Zeitangaben in den verschiedenen Ressourcen in dem Bundle sind nicht stimmig. Wenn zB die Blutdruckmessung zu dem im Bundle enthaltenen Encounter gehören soll, dann sollte das Datum der Messung auch zwischen Anfangs- und Enddatum des Encounters liegen.
2. Das Bundle soll ja als Rückübermittlung von einem Subsystem zum KIS geschickt werden. In diesem Fall kann das ja ein vernetztes Blutdruckmessgerät oder ein Laborsystem sein. Dieses wird aber sicherlich nicht so detaillierte Informationen zum Patienten und zum Encounter haben, wie dies in dem Beispiel angegeben ist. Diese Informationen in der Detailtiefe hat sicher nur das KIS. Grundsätzlich scheint es mir auch vorgesehen, dass aus diesem Grund das Subsystem Patient- und Encounter-Ressource nur als "Rumpf" sendet, denn die Spezifikation geht eh davon aus, dass das KIS diese Daten nicht übernimmt, sondern nur die Existenz von Patient und Encounter verifiziert: _Falls die im Dokumenten-Bundle enthaltene Patient-Ressource und/oder Encounter-Ressource nicht anhand der Business-Identifier oder anderer Matching-Kriterien im empfangenden System gefunden werden kann (d.h. der Patient oder der Encounter existiert im empfangenden System noch nicht), MUSS als Antwort der HTTP Status Code "422 - Unprocessable Entity" zurückgegeben werden._ (siehe https://simplifier.net/guide/implementierungsleitfadenisik-basismodul/ImplementationGuide-markdown-Datenobjekte-Datenobjekte-BerichtSubsystem?version=current). 
3. Grundsätzlich fände ich es sinnvoll, für dieses (und auch einige andere) Beispiel zunächst eine kleine Story zu schreiben, so in der Art "Der Patient X war vom 3. bis 5. Mai 2022 als stationärer Fall im Krankenhaus. Dabei wurde am 3. Mai der Blutdruck gemessen und das Ergebnis im LIS vermerkt. Das LIS sendet das Messergebnis an das KIS, so dass das KIS dieses in die Gesamtdokumentation zum Patienten aufnehmen kann." Auf der Basis wird dann auch das Beispiel besser verständlich.

**Comment by f-peverali** [comment]
User Story füge ich in die Description des Bundle-Example ein. Ggf. auch in IG einarbeiten (wenn, dann überall kohärent)?

**Comment by f-peverali** [comment]
@jcaumann so besser? https://github.com/gematik/spec-ISiK-Basismodul/pull/142/files

**Comment by jcaumann** [comment]
@f-peverali : Der timestamp in Zeile 30 ist noch falsch (da steht März, richtig wäre Mai). Auch würde ich bei der MusterfrauMinimal die extensions alle weglassen. Die sind in dem Profil alle optional ([0..1]) und wir sollten nicht davon ausgehen, dass ein Subsystem/Peripheriegerät in der Lage ist, einen Namen über Name, Vorname, Titel hinaus aufzuschlüsseln.

**Comment by alexzautke** [comment]
Ich würde zudem keine OID als Identifier Value verwenden, sondern ein eigenes NamingSystem, setzt sonst ein schlechtes Beispiel.

**Comment by alexzautke** [comment]
Zudem geht es bei der Rückübermittelung des Bundles hauptsächlich um das Narrative, dass übernommen werden soll. Dieses fehlt auch noch.

**Comment by jcaumann** [comment]
@alexzautke , @f-peverali : das mit den OIDs wäre auch eine gute Ergänzung zu den Designprinzipien in https://wiki.gematik.de/pages/viewpage.action?pageId=492832129

**Comment by f-peverali** [comment]
- [ ] timestamp ändern
- [ ] extensions bei Patient entfernen
- [ ] OID ersetzen mit NamingSystem
- [ ] Narrative ergänzen

**Comment by f-peverali** [comment]
> Ich würde zudem keine OID als Identifier Value verwenden, sondern ein eigenes NamingSystem, setzt sonst ein schlechtes Beispiel.

Wo finde ich eine Best-Pracitce zur Nutzung eines NamingSystems als Identifier für die Beispiel Composition?

Im IG steht momentan:

> Composition.identifier
> Bedeutung: Subsystem-seitig zugewiesener Identifier des Berichtes mit Angabe der URL des vom Subsystem verwendeten Namensraumes
> 
> Hinweise: **Die Verwendung von OIDs ist möglich. Dafür KANN folgendes Format verwenden:**
> 
> Das Feld system enthält den festen Wert "urn:ietf:rfc:3986"
> Das Feld value enthält die OID mit dem Präfix "urn:oid:"
> Beispiel:
> <identifier>
>     <system value="urn:ietf:rfc:3986"/>
>     <value value="urn:oid:2.16.840.1.113883.6.96"/>
> </identifier>

Das würde ich dann bestenfalls auch anpassen.

**Comment by alexzautke** [comment]
Ich würde es umformulieren in "Die Verwendung von OIDs ist möglich jedoch nicht empfohlen." Gerne kann auch hier auf die Seite der Deutschen Basisprofile verlinkt werden: https://simplifier.net/guide/leitfaden-de-basis-r4/ig-markdown-Terminologie-Namensraeume?version=current

**Comment by f-peverali** [comment]
Habe hier https://github.com/gematik/spec-ISiK-Basismodul/pull/142/commits/7a1e553843d7654bbb2c2168be4a2a9fd5060209 den Hinweis in der IG geändert und würde ggf. auch das OID-Beispiel entfernen, sonst wirkt es inkohärent, da davon abgeraten wird OIDs zu nutzen.

**Comment by f-peverali** [comment]
Passt das Narrative? Ich habe hier auch noch das Section narrative eingefügt mit den Blutdruck-Werten. So sinnvoll?

**Comment by alexzautke** [comment]
Ich werde morgen einmal testen ob unser System (Firely Server) das Bespiel via der Rückübermittlungsapi entgegen nehmen würden.

**Comment by f-peverali** [comment]
TODO: section entries entfernen
Hintergrund: Patient und Encounter als section sind nicht sinnvoll (abgestimmt mit fbeta und gefyra)
