### ISSUE TITLE
Encounter.account.identifier muss besser spezifiziert werden (Stufe 3)

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Basismodul#65]
identifier.type = AN (Account Number) statt VN?
Pflichtfelder?
MustSupport-Felder?

Beispiele überprüfen!!

**Comment by f-peverali** [comment]
IST-Zustand: 
Encounter.identifier.Aufnahmenummer.type.coding.code = VN
Account.identifier.Aufnahmenummer.type.coding.code = VN

Fragen:
1) Sollte "Account.identifier..." nicht eher angepasst werden (und auf der Grundlage ggf. Slicing in Encounter.account ?)
2) Warum derzeitige "Pflichtfelder gewählt?
3) Wie MS prüfen? Nach welchen Kriterien?
4) aktuelles Beispiel sagt iun bezug auf Abrechnung nicht viel mehr aus, als dass es sich um einen aktike DRG handelt (denr DRG-Code selbst noch unklar.; siehe Ticket ...)

**Comment by f-peverali** [comment]
@simoneOnFhir könntest DU mir nochmal Input zu Frage 1 (s.o.) geben. Wie ist es gemeint? Soll die Account Ressource modifiziert werden mit account.identifier.type.code = AN ?

**Comment by simoneOnFhir** [comment]
zu 1. Das Problem ist halt die Frage: Ist ein Account-Identifier("Abrechnungsnummer" das gleiche wie eine "Aufnahmenummer"? Die Basisprofile beschreiben das letztere. Aber das trifft hier nicht (zwangsläufig) zu. Unter einer Abrechnungsnnummer können mehrere Aufnahmen zusammengefasst werden (z.B. bei mehreren nachstationären Besuchen oder Wiederaufnahme)

**Comment by f-peverali** [comment]
Ok, danke Simone. 
A) In diesem Sinne würde ich dazu tendieren den ISiK Account-Identifier als eigenständigen Typ aufzufassen und auch entsprechend eigenständig und damit differenzierbar zu Codieren als "AN" Account number ~ Abrechnungsnummer. 
B) Unschön fände ich dabei aber den dann nötigen Bruch mit der Basisprofil-De Identifier zum Account - siehe Identifier.type hier https://simplifier.net/packages/de.basisprofil.r4/1.4.0/files/656784 

@AnsgarHoeper was denkst Du zu A)
@simoneOnFhir wie sollten wir als ISiK-Team mit dem Umstand in B) umgehen? Einfach "unser Ding machen" jenseits der Basisprofile halte ich für unschön...

**Comment by alexzautke** [comment]
Wir könnten in den Basisprofilen einen neuen Identifier für Abrechnungsnummer definieren. +1 für VN als .type.

**Comment by f-peverali** [comment]
> Wir könnten in den Basisprofilen einen neuen Identifier für Abrechnungsnummer definieren 
-> das fände ich super

> +1 für VN als .type.
-> hierfür haben wir die Lösung bei Identifier.type hier https://simplifier.net/packages/de.basisprofil.r4/1.4.0/files/656784
.. wie wäre es mit einem neuen Profil für einen Abrechnungsnummer-Identifier (u.a. für den ISiKAccount) zur Bündelung einzelner Encounter / Fälle mit Identifier.type = AN (Account number)?

**Comment by f-peverali** [comment]
hier für ggf. ADR anlegen

**Comment by f-peverali** [comment]
Eine Lösung wurde im Rahmen des TC FHIR beschlossen (Protokoll _ https://hl7germany.sharepoint.com/:w:/s/TCFHIR/EQ-y2fWL5AhMuhfqSTuDJuAB1EfOdQGMPEs0nXPxkNkzSA?rtime=629N9sn_2kg) . 

Die Umsetzung erfolgt im Rahmen der Stufe 3 und wird auch in die Basisprofile DE eingehen.

**Comment by f-peverali** [comment]
TODO (sobald review für Basis De durch)
- [ ] Einarbeiten in Stufe 3

**Comment by f-peverali** [comment]
Zum review hier https://github.com/gematik/spec-ISiK-Basismodul/pull/238
