### ISSUE TITLE
Beispiel Name inkorrekt

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Basismodul#66]
* name[=].family = "Fürstin von Musterfrau"
  * extension[0].url = "http://fhir.de/StructureDefinition/humanname-namenszusatz"
  * extension[=].valueString = "Graf"
  * extension[+].url = "http://hl7.org/fhir/StructureDefinition/humanname-own-name"
  * extension[=].valueString = "Musterfrau"
  * extension[+].url = "http://hl7.org/fhir/StructureDefinition/humanname-own-prefix"
  * extension[=].valueString = "von"

**Comment by f-peverali** [comment]
hier gelöst https://github.com/gematik/spec-ISiK-Basismodul/pull/94
