### ISSUE TITLE
NS URL sollte best practice folgen

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Basismodul#68]
* identifier[+].type = $v2-0203#MR
* identifier[=].system = "https://fhir.krankenhaus.example/NamingSystem/PID"
* identifier[=].value = "TestPID"

/NamingSystem/ -> /sid/

**Comment by f-peverali** [comment]
solved in https://github.com/gematik/spec-ISiK-Basismodul/commit/924de8102bbdf096b83b9b6cb55a6f8bc82fe771
