### ISSUE TITLE
Practitioner - Binding qualification

### ISSUE THREAD

**Issue by abiernat-cerner** [gematik/spec-ISiK-Basismodul#74]
Hallo zusammen, 
beid der Implementierung von ISiK 1.0 als auch in ISiK 2.0 sind Probleme mit dem Binding zum Practitioner augefallen.
Im Profil wird heute auf das ValueSet https://fhir.kbv.de/ValueSet/KBV_VS_Base_Practitioner_Speciality verwiesen (preferred).
Daraus ergeben sich folgende Probleme:

* Eine Abbildung der Profession Arzt ist nicht korrekt möglich. Es wird im VS https://fhir.kbv.de/ValueSet/KBV_VS_Base_Practitioner_SNOMED nur das Konzept Practitioner inkludiert. Somit werden aber Chirugen exludiert. Hier müsste m.E. ein VS mit den Konzept 158965000 |Medical practitioner (occupation)| und relevanten Kind-Konzepten sein um alle Ärzte in Snomed zu erfassen.
* Fur Abbildung von Pflegekräften fehlt die Nutzung des Snomed CT Konzepts. Es empfiehlt sich hier mit 106292003 |Professional nurse (occupation)| zu arbeiten. Statt mit dem KBV CS und Konzept PF.

**Comment by f-peverali** [comment]
Vielen Dank für den Input. 
Es wäre wünschenswert ein SNOMED-basiertes VS zu verknüpfen. 
Ein Abweichen von den KBV-VS halte ich allerdings für problematisch (auch weil noch keine Deutsche SNOMED Übersetzung existiert). 
Ein Chirurg kann z.B. nach KBV-VS Codiert werden mit 71107 - FA Allgemeinchirurgie (oder mit einer spezialisierten chirurgischen FA-Bezeichunng). Die Entscheidung hier die Präzision der Codierung einem potentiell höheren Recall bei Suchabfragen den Vorzug zu geben, halte ich für vertretbar.
Für Abbildung von Pflegekräften werden verschiedene spezialisierte Pflegefachberufe gelistet und die neu geschaffene Berufsbezeichnung "Pflegefachmann/Pflegefachfrau". 
Daher würde ich auch hier von einer Abweichung vom KBV-VS absehen. 
Sollten dennoch weitere Konzepte fehlen, würde ich persönlich auf die KBV einwirken diese aufzunehmen. 
In jedem Fall werde ich den Kontakt zu KBV/MIO42 suchen und diesen Kommentar teilen.

**Comment by f-peverali** [comment]
zusatz: Das preferred binding ermöglicht die Erweiterung um jegliche SNOMEd Ct Codes
