### ISSUE TITLE
Condition.code.coding:Alpha-ID verwendet nicht Profil aus den Deutschen Basisprofilen

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Basismodul#86]
AlphaID-Profil aus den Deutschen Basisprofilen sollte in Stufe 1 verwendet werden

**Comment by alexzautke** [comment]
Siehe https://simplifier.net/guide/leitfaden-de-basis-r4/ig-markdown-Datentypen-Coding?version=current#ig-markdown-Datentypen-Coding-Alpha-ID

**Comment by alexzautke** [comment]
Sollte am Ende aussehen wie in Stufe 1: https://simplifier.net/isik-basis-1/isikdiagnose

**Comment by f-peverali** [comment]
hier korrigiert : https://github.com/gematik/spec-ISiK-Basismodul/commit/4e04a134dafcc7f932a574a7b4b5bbe61dc0295d

**Comment by f-peverali** [comment]
@patrickwladowska sollte gelöst sein.
