### ISSUE TITLE
sct-ops-1 in v2.0.0 fehlerhaft

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Basismodul#89]
aus 1.0.3 übernehmen

**Comment by alexzautke** [comment]
Siehe ISiKProzedur 1.0.4

**Comment by f-peverali** [comment]
gelöst mit [#110](https://github.com/gematik/spec-ISiK-Basismodul/issues/110) ?

**Comment by alexzautke** [comment]
Ja, Problem ist damit erledigt.
