### ISSUE TITLE
TC 1 und 2- Rückübermittlung Bericht aus Subsystemen (Composition)

### ISSUE THREAD

**Issue by patrick-werner** [gematik/spec-ISiK-Basismodul#96]
section.text.status ist im Profil nicht als fixed value gesetzt (vgl. Composition.text)

Dies sollte alligned werden: section.text.status sollte den fixed value "extensions" erhalten

**Comment by alexzautke** [comment]
Sollte in Stufe 1 und Stufe 2 korrigiert werden

**Comment by f-peverali** [comment]
leider zu alt und obsolet
