### ISSUE TITLE
Alle Ressourcen in ISiK Stufe 2: .id sollte eine Kardinalität von 0..1 enthalten

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Basismodul#97]
Die Änderungen aus ISiK 1.0.4 sind in ISiK 2.0.0 nicht enthalten aufgrund eines Fehlers im Umgang mit Git.

**Comment by f-peverali** [comment]
Das sollte weitgehend umgesetzt sein @patrickwladowska 
Ggf. nochmal review durchführen?
