### ISSUE TITLE
Technical Correction für Package ID Stufe 1 / Stufe 2

### ISSUE THREAD

**Issue by alexzautke** [gematik/spec-ISiK-Basismodul#98]
Die Version 1.0.4 wurde nur mit der Package ID "de.gematik.isik-basismodul-stufe1" veröffentlicht. Alle vorherigen Versionen unter "de.gematik.isik-basismodul". Die Technical Correction v1.0.5 sollte unter dem Namen "de.gematik.isik-basismodul" veröffentlicht werden.

**Comment by f-peverali** [comment]
FYI @patrickwladowska

**Comment by f-peverali** [comment]
haben wir hierzu einen Beschölus @patrickwladowska ? ,#Releasemanagement

**Comment by f-peverali** [comment]
Leider ist die Stufe 1 jetzt "konsequent inkohärent" mit "de.gematik.isik-basismodul-stufe1" released. Stufe 2 dagegen mit package ID "de.gematik.isik-basismodul". Ich kann die Auswirkungen nicht absehen.
Wie sollten wir vorgehen?
Unklar für mich wo hier der Parameter korrekt gesetzt werden sollte:
- package.json
- ImplmentierungsleitfadenIsiJ_basismodul.json
- sushi_config.yaml
In diesen Dateien in Stufe 1 und 2 inkohärente Bezeichnungen
@alexzautke könntest Du mir hier nochmal weiterhelfen?

FYI @jcaumann

**Comment by alexzautke** [comment]
Ich habe gerade keine Idee wie man das wieder gerade biegen kann. Auswirkungen hat es nur für die Entwickler die direkt die Packages verwenden. Zukünftig wäre ich persönlich dafür, dass alle Packages unter "de.gematik.isik-basismodul" einsortiert werden, sodass man nicht so viel suchen muss.

**Comment by f-peverali** [comment]
Auch packageid in Stufe zwei noch inkohärent - siehe : https://simplifier.net/isik-basis-v2/implementationguide-implementierungsleitfadenisik-basismodul

**Comment by f-peverali** [comment]
rückwirkend nicht anpassbar (für stufe 1 und 2)
