### ISSUE TITLE
Differential zwischen Stufe 1 und Stufe 2 erstellen

### ISSUE THREAD

**Issue by patrickwladowska** [gematik/spec-ISiK-Basismodul#99]
Für die Basismodule ein Diff zwischen den Basismodulen erstellen und die Auffälligkeiten betrachten.

**Comment by patrickwladowska** [comment]
@f-peverali die Anpassungen können nun für die 2.0.2. vorbereitet werden.

**Comment by f-peverali** [comment]
> @f-peverali die Anpassungen können nun für die 2.0.2. vorbereitet werden.

Die Änderungen für Stufe zwei sind in TC_2.0.2

**Comment by f-peverali** [comment]
@patrickwladowska für die Basisstufe 1 würde ich auch jetzt einen TC_1.0.6 Branch erzeugen und die nötigen Änderungen commiten. Ok?

**Comment by f-peverali** [comment]
TC Stufe 1 hier eingearbeitet: https://github.com/gematik/spec-ISiK-Basismodul/pull/106/commits/df838218d761b00bdffc625b0c4c1e6ac9009124

**Comment by f-peverali** [comment]
* period
  * start ^mapping.identity = "KVDT"
  * start ^mapping.map = "4133"
  * end ^mapping.identity = "KVDT"
  * end ^mapping.map = "4110"

... noch in klärung

**Comment by f-peverali** [comment]
das mapping zu kvdt würde ich in basis drin lassen und das ticket schließen, ok @alexzautke ?

**Comment by alexzautke** [comment]
Ok
